services:
  emsi-discovery-service:
    build: ./discovery-service
    container_name: emsi-discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"] # <--- This is the health check
      interval: 10s

  emsi-config-service:
    build: ./config-service
    container_name: emsi-config-service
    ports:
      - "9999:9999"
    expose:
      - "9999"
    environment:
      - DISCOVERY_SERVICE_URL=http://emsi-discovery-service:8761/eureka
    depends_on:
      emsi-discovery-service:
        condition: service_healthy

#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"] # <--- This is the health check
#      interval: 10s