services:
  emsi-discovery-service:
    build: ./discovery-service
    container_name: emsi-discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"] # <--- This is the health check
      interval: 10s
      retries: 2

  emsi-config-service:
    build: ./config-service
    container_name: emsi-config-service
    ports:
      - "9999:9999"
    expose:
      - "9999"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ] # <--- This is the health check
      interval: 10s
      retries: 2
    environment:
      - DISCOVERY_SERVICE_URL=http://emsi-discovery-service:8761/eureka
    depends_on:
      emsi-discovery-service:
        condition: service_healthy

  emsi-customer-service:
    build: ./customer-service
    container_name: emsi-customer-service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ] # <--- This is the health check
      interval: 10s
      retries: 2
    environment:
      - DISCOVERY_SERVICE_URL=http://emsi-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://emsi-config-service:9999
    depends_on:
      emsi-config-service:
        condition: service_healthy

  emsi-account-service:
    build: ./account-service
    container_name: emsi-account-service
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      - DISCOVERY_SERVICE_URL=http://emsi-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://emsi-config-service:9999
    depends_on:
      emsi-customer-service:
        condition: service_healthy

  emsi-gateway-service:
    build: ./gateway-service
    container_name: emsi-gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
     - DISCOVERY_SERVICE_URL=http://emsi-discovery-service:8761/eureka
     - CONFIG_SERVICE_URL=http://emsi-config-service:9999
    depends_on:
      emsi-config-service:
        condition: service_healthy
  front-end-angular:
    build: ./angular-front-end
    container_name: front-end-angular
    ports:
      - "80:80"
    expose:
        - "80"

#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"] # <--- This is the health check
#      interval: 10s