spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-headers: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
